### teste

GET http://localhost:3003/ping

### get all users
GET http://localhost:3003/users

### Get All Products

GET http://localhost:3003/products

### Get All Products by name

GET http://localhost:3003/products?name=Mouse

### Create Users

POST http://localhost:3003/users
content-type: application/json

{
    "id": "0001",
    "name": "Regi",
    "email": "beltrana@email.com",
    "password": "cheguei"
}

### Create Products

POST http://localhost:3003/products
content-type: application/json

{
    "id": "prod001",
    "name": "Tablet",
    "price": 1000,
    "description": "Da aplle",
    "imageUrl": "nao tem"
}


### DElete User By Id

DELETE http://localhost:3003/users/4

### Delete Product by id

DELETE http://localhost:3003/products/prod001

### Edit Product by id

PUT http://localhost:3003/products/7
content-type: application/json

{
    "id": "3",
    "name": "Regi",
    "price": 200,
    "description": "cheguei",
    "imageUrl": "nao tenho"
}